<a href="https://colab.research.google.com/github/rajat4057/PythonBase/blob/master/Filter_n_sort_Exercises2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ex2 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.

### Step 1. Import the necessary libraries

In [0]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

### Step 3. Assign it to a variable called euro12.

In [0]:
euro12=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv')

In [3]:
euro12.head(2)

             Team  Goals  Shots on target  ...  Subs on Subs off Players Used
0         Croatia      4               13  ...        9        9           16
1  Czech Republic      4               13  ...       11       11           19

[2 rows x 35 columns]

### Step 4. Select only the Goal column.

In [5]:
euro12['Goals']

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

### Step 5. How many team participated in the Euro2012?

In [8]:
euro12['Team'].nunique()

16

### Step 6. What is the number of columns in the dataset?

In [10]:
euro12.shape[1]

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [0]:
discipline=euro12[['Team','Yellow Cards','Red Cards']]

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [15]:
euro12.sort_values(['Red Cards','Yellow Cards'],ascending=False)

                   Team  Goals  ...  Subs off  Players Used
6                Greece      5  ...        12            20
9                Poland      2  ...         7            17
11  Republic of Ireland      1  ...        10            17
7                 Italy      6  ...        18            19
10             Portugal      6  ...        14            16
13                Spain     12  ...        17            18
0               Croatia      4  ...         9            16
1        Czech Republic      4  ...        11            19
14               Sweden      5  ...         9            18
4                France      3  ...        11            19
12               Russia      5  ...         7            16
3               England      5  ...        11            16
8           Netherlands      2  ...         7            15
15              Ukraine      2  ...         9            18
2               Denmark      4  ...         7            15
5               Germany     10  ...        15            17

[16 rows x 35 columns]

### Step 9. Calculate the mean Yellow Cards given per Team

In [18]:
euro12.groupby('Team')['Yellow Cards'].mean()

Team
Croatia                 9
Czech Republic          7
Denmark                 4
England                 5
France                  6
Germany                 4
Greece                  9
Italy                  16
Netherlands             5
Poland                  7
Portugal               12
Republic of Ireland     6
Russia                  6
Spain                  11
Sweden                  7
Ukraine                 5
Name: Yellow Cards, dtype: int64

### Step 10. Filter teams that scored more than 6 goals

In [21]:
euro12[euro12['Goals']>6]['Team']

5     Germany
13      Spain
Name: Team, dtype: object

### Step 11. Select the teams that start with G

In [24]:
euro12[euro12.Team.str.startswith('G')]

      Team  Goals  Shots on target  ...  Subs on Subs off Players Used
5  Germany     10               32  ...       15       15           17
6   Greece      5                8  ...       12       12           20

[2 rows x 35 columns]

### Step 12. Select the first 7 columns

In [31]:
euro12.iloc[:,:8]

                   Team  Goals  ...  Total shots (inc. Blocked)  Hit Woodwork
0               Croatia      4  ...                          32             0
1        Czech Republic      4  ...                          39             0
2               Denmark      4  ...                          27             1
3               England      5  ...                          40             0
4                France      3  ...                          65             1
5               Germany     10  ...                          80             2
6                Greece      5  ...                          32             1
7                 Italy      6  ...                         110             2
8           Netherlands      2  ...                          60             2
9                Poland      2  ...                          48             0
10             Portugal      6  ...                          82             6
11  Republic of Ireland      1  ...                          28             0
12               Russia      5  ...                          59             2
13                Spain     12  ...                         100             0
14               Sweden      5  ...                          39             3
15              Ukraine      2  ...                          38             0

[16 rows x 8 columns]

### Step 13. Select all columns except the last 3.

In [32]:
euro12.iloc[:,:-3]

                   Team  Goals  ...  Yellow Cards  Red Cards
0               Croatia      4  ...             9          0
1        Czech Republic      4  ...             7          0
2               Denmark      4  ...             4          0
3               England      5  ...             5          0
4                France      3  ...             6          0
5               Germany     10  ...             4          0
6                Greece      5  ...             9          1
7                 Italy      6  ...            16          0
8           Netherlands      2  ...             5          0
9                Poland      2  ...             7          1
10             Portugal      6  ...            12          0
11  Republic of Ireland      1  ...             6          1
12               Russia      5  ...             6          0
13                Spain     12  ...            11          0
14               Sweden      5  ...             7          0
15              Ukraine      2  ...             5          0

[16 rows x 32 columns]

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [38]:
euro12[(euro12['Team']=='England')|(euro12['Team']=='Italy')|(euro12['Team']=='Russia')][['Shooting Accuracy','Team']]

   Shooting Accuracy     Team
3              50.0%  England
7              43.0%    Italy
12             22.5%   Russia